### PR TITLE
As a Kperf developer, I want to refine service generate/measure flags code comments and etc

### PR DESCRIPTION
**Pull request by qibobo**

### CODE REVIEW

**Review by maximilien — CHANGES_REQUESTED** [review]
Left one important comment and also what about having some tests :) I would suggest e2e tests first so that way changes like this can be verified from the user’s perspective. Unit tests would work too but unless you are adding UTs as you are adding code it’s a huge task to backfill them.

**Comment by zhanggbj** [comment]
@chizhg @evankanderson Yang(@qibobo ) is from our team and currently focusing on kperf development, would you please help to add him in knative-sandbox org, thanks in advance!

**Comment by evankanderson** [comment]
Yang will need to add themselves to http://github.com/knative/community/tree/master/peribolos/knative-sandbox.yaml, which will send them an invite to join the org. They'll also need to accept the org invite when they receive it, because you can't add a GitHub user to an org without their consent.

**Comment by zhanggbj** [comment]
@evankanderson  got it, thanks a lot for your info!

**Comment by qibobo** [comment]
@maximilien 
There is another issue to track the tests and we will fix it in another PR.
https://github.com/knative-sandbox/kperf/issues/5

**Comment by qibobo** [comment]
Hi @maximilien , PR updated. Could you review the changes? Thx.

**Comment by zhanggbj** [comment]
@qibobo 
Please help to rebase your PR. And if @maximilien has no more comments, then we can merge it. Thanks!

**Comment by qibobo** [comment]
@zhanggbj 
The commit https://github.com/knative-sandbox/kperf/commit/db2091b87ac0c7f5d1833b7b867ab78b32829585 has breaked the design of generator and cleaner, I prefer to discuss it in tmw's meeting before I do the rebase.

**Review by maximilien — APPROVED** [review]
Sweet. Looking good to me. I’ll wait a day for others to review before adding lgtm

**Comment by qibobo** [comment]
@zhanggbj  rebased.

**Review by zhanggbj — APPROVED** [review]

**Comment by zhanggbj** [comment]
This looks good. Thanks @qibobo for the efforts.

As 2 PRs (https://github.com/knative-sandbox/kperf/pull/23, https://github.com/knative-sandbox/kperf/pull/15) are pending on this change and they all need a rebase to continue their work, so I'll merge it today.

CC @maximilien 

/lgtm
/assign @maximilien

**Pull request merged**
