### PR TITLE
add test infra related stuffs

### PR DESCRIPTION
**Pull request by zyjiaobj**

### CODE REVIEW

**Comment by zhanggbj** [comment]
@chizhg @evankanderson Yajiao(@zyjiaobj) is from our team and currently focusing on kperf development, would you please help to add her in knative-sandbox org, thanks in advance!

**Comment by zyjiaobj** [comment]
@chizhg As you mentioned that, the error in the prow means that there is no coverage history saved in COS bucket because `kperf` is a totally new project:
```
2020/11/12 12:23:34 No build found for bucket 'knative-prow' and object 'logs/post-knative-sandbox-kperf-go-coverage'
```
This may be a bug related to https://github.com/knative/test-infra. Do you know there is any plan/issue tracking to fix it?

We hope this PR can totally pass the prow check, if this issue is not fixed this time, we may encounter it again. Thanks!

**Comment by zhanggbj** [comment]
Just for future reference, the go-coverage job is replaced by codecov as PR here https://github.com/knative/test-infra/pull/2586

**Review by zhanggbj — APPROVED** [review]

**Comment by zhanggbj** [comment]
/lgtm

Thanks @zyjiaobj for the efforts! Merging it, and we will keep an eye about `codecov` result (So far it is not in the check list).

**Pull request merged**
