### PR TITLE
Enable vendoring via hack/update-deps.sh

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title.

This enables vendoring like we do for all Knative repos and vendors things via the usual `hack/update-deps.sh` script, which also makes sure, that the vendored licenses are correct etc.

### CODE REVIEW

**Review by zhanggbj — APPROVED** [review]
a large PR with lots of vendor files.

**Review by gyohuangxin — APPROVED** [review]
lgtm

**Comment by markusthoemmes** [comment]
@zhanggbj or @maximilien I believe this needs another approval (as-in Github approval) from one of you to make this merge. We changed the way the auto-merges work in the meantime.

**Review by zhanggbj — APPROVED** [review]

**Pull request merged**
