### PR TITLE
WIP: first shot at eventing prepare framework. Add KafkaSource scenario

### PR DESCRIPTION
**Pull request by lionelvillard**
# Changes

- Sketch eventing prepare framework. Introduce notion of "scenarios"
- Add Minimal KafkaSource scenario (KafkaSource* -> HTTP receiver)
- Add `eventing prepare list` command to list all available testing scenarios
- Add `eventing prepare kafkaSource` to create/update the `kafkasource` scenario 
-

/kind enhancement

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

This is WIP and it's not yet functional. The big gap is how/where to publish the kperf image. Might get inspired by reconciler-test

Depends on https://github.com/knative-sandbox/kperf/pull/71

### CODE REVIEW

**Review by maximilien — COMMENTED** [review]
/ok-to-test

Reviewing this...taking time since it’s pretty large. Any chance to break this into multiple PRs @lionelvillard ?

**Comment by lionelvillard** [comment]
@maximilien This PR is actually quite small. It includes Alek's work. Please wait for Alek's PR to be merged and then I'll rebase it.

**Comment by maximilien** [comment]
Aha, thanks for clarification @lionelvillard

**Comment by maximilien** [comment]
@aslom ^^^

**Comment by maximilien** [comment]
Waiting on rebase to review...

**Pull request closed without merging**
