### PR TITLE
Update to go 1.17

### LINKED ISSUE #203: Update to go version 1.17 to avoid build errors
When I run `./hack/build.sh`
I got below errors:
```
# sigs.k8s.io/json/internal/golang/encoding/json
../../../../pkg/mod/sigs.k8s.io/json@v0.0.0-20211208200746-9f7c6b3444d2/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
../../../../pkg/mod/sigs.k8s.io/json@v0.0.0-20211208200746-9f7c6b3444d2/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
note: module requires Go 1.17
```

I also noticed serving and client have already update to go 1.17. So I propose we do the same in kperf.

### PR DESCRIPTION
**Pull request by daisy-ycguo**
Fixes #203 

# Changes
- :broom: Update to go 1.17

### CODE REVIEW

**Review by zhanggbj — COMMENTED** [review]
Hey Daisy @daisy-ycguo ,

Looks like there's an extra binary file (kperf) in the commit, please take a look, thx!

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

Thanks for doing this

**Comment by daisy-ycguo** [comment]
> Hey Daisy @daisy-ycguo ,
> 
> Looks like there's an extra binary file (kperf) in the commit, please take a look, thx!

Thank you for review. I've removed the binary and rebased. Please review again.

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

Thanks Daisy

**Pull request merged**
