### PR TITLE
Add all client-go authenticators

### PR DESCRIPTION
**Pull request by howardjohn**
otherwise I cannot run this on my GKE cluster. See https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L34

Basically you cannot run this against a lot of clusters (GKE in my case) without importing the auth libraries

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
Can you add a bit more details. Happy to merge it but want to capture a little more details for posterity.
/ok-to-test
/approve

**Comment by howardjohn** [comment]
https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L34

Basically you cannot run this against a lot of clusters (GKE in my case) without importing the auth libraries

**Comment by howardjohn** [comment]
Ping @maximilien

**Pull request merged**
